### PR TITLE
220 time as factor

### LINKED ISSUE #220: Clarify in documentation that non-spatial covariance structure needs factor variable
Motivation: As shown in https://github.com/openpharma/mmrm/issues/217 it is not obvious right now that time point variable needs to be factor variable for non-spatial covariance structures.

To do:

- [x] Clarify in
	- [x] intro vignette
	- [x] `mmrm()` doc
	- [x] `cov_type` doc
- [x] Improve error message: Currently the user gets `Assertion on 'coordinates[[1L]]' failed: Must be of type 'factor', not 'double'` and they should get something like `Time points variable needs to be a factor`

### PR DESCRIPTION
**Pull request by danleibovitz**
closes #220 

- Inserts a check and corresponding error message in R/tmb.R, within the fit_mmrm() function; add a corresponding test in test-tmb.R under 'misc'.
- Updates the documentation in R/fit.R for mmrm(), in cov_struct.R for cov_types, and in the intro vignette.

### CODE REVIEW

File: R/cov_struct.R [hunk 1]
```diff
@@ -133,6 +133,9 @@ COV_TYPES <- local({  # nolint
 #' from SAS `PROC MIXED` refers to heterogeneous ante-dependence and the
 #' homogeneous version is not available in SAS.
 #'
+#' Note that for all non-spatial covariance structures, the time variable must
```
Comment (danielinteractive) [inline R/cov_struct.R:136]: maybe add this and above note under `@note` section

File: R/tmb.R [hunk 2]
```diff
@@ -472,6 +472,8 @@ fit_mmrm <- function(formula,
   covariance <- reconcile_cov_struct(formula, covariance)
   formula_parts <- h_mmrm_tmb_formula_parts(formula, covariance)
 
+  if (!formula_parts$is_spatial && !is.factor(data[[formula_parts$visit_var]])) stop("Time variable must be a factor for non-spatial covariance structures")
```
Comment (danielinteractive) [inline R/tmb.R:475]:
```suggestion
  if (!formula_parts$is_spatial && !is.factor(data[[formula_parts$visit_var]])) {
    stop("Time variable must be a factor for non-spatial covariance structures")
  }
```

File: R/fit.R [hunk 3]
```diff
@@ -359,6 +360,8 @@ mmrm <- function(formula,
   if (control$method %in% c("Kenward-Roger", "Kenward-Roger-Linear") && !reml) {
     stop("Kenward-Roger only works for REML")
   }
+  # TODO insert informative error message if cov struc is non-spatial and time point variables is not factor
```
Comment (danielinteractive) [inline R/fit.R:363]:
```suggestion
```

File: R/tmb.R (hunk 2 above)
Comment (danielinteractive) [reply R/tmb.R:475]: I wonder though, now that we have the `validate_cov_struct()` function, would this assertion better fit there? can you please check?

**Review by danielinteractive — COMMENTED** [review]
thanks a lot @danleibovitz ! please see inside

File: R/cov_struct.R (hunk 1 above)
Comment (danleibovitz) [reply R/cov_struct.R:136]: Good point, done.

File: R/tmb.R (hunk 2 above)
Comment (danleibovitz) [reply R/tmb.R:475]: I don't think the `validate_cov_struct()` as is helps us here because the object is valid by construction. We could: 

1. Write a new `checkmate` style check, e.g., `validate_time_as_factor()`,
2. Include a new check within the `validate_cov_struct()` definition, and then run it here.

File: R/fit.R (hunk 3 above)
Comment (danleibovitz) [reply R/fit.R:363]: This is a silly oversight on my part -- text removed.

File: R/tmb.R (hunk 2 above)
Comment (danielinteractive) [reply R/tmb.R:475]: Hm ok, then let's keep it as is. Thanks for checking!

**Review by danielinteractive — APPROVED** [review]

**Review by danielinteractive — APPROVED** [review]
