### PR TITLE
fix bug of interaction only models

### LINKED ISSUE #261: interaction-only formulas seem to make trouble
To do:

- [x] Add a unit test for this bug
- [x] Check whether the test fails also with the current CRAN version of `mmrm` installed - seems to be the case
	- [x] only if yes, then make a NEWS entry for the bug fix
- [x] Fix the bug
- [x] Confirm all tests pass

**Summary**

interaction-only formulas seem to make trouble

```
library(mmrm)
mmrm(
    formula = FEV1 ~ ARMCD * AVISIT + us(AVISIT | USUBJID),
    data = fev_data
)
```

works fine but interaction only does not

```
mmrm(
    formula = FEV1 ~ ARMCD : AVISIT + us(AVISIT | USUBJID),
    data = fev_data
)
```

and returns 

```
Error in terms.formula(newformula, specials = names(attr(termobj, "specials"))) :
invalid model formula in ExtractVars
```

**R session info**

```
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] mmrm_0.2.2.9014

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10         lattice_0.20-45     rbibutils_2.2.13   
 [4] grid_4.2.2          R6_2.5.1            lifecycle_1.0.3    
 [7] nlme_3.1-160        backports_1.4.1     magrittr_2.0.3     
[10] httr_1.4.5          stringi_1.7.12      Rdpack_2.4         
[13] rlang_1.1.0         cli_3.6.0           rstudioapi_0.14    
[16] Matrix_1.5-1        checkmate_2.1.0     tools_4.2.2        
[19] TMB_1.9.2           stringr_1.5.0       glue_1.6.2         
[22] parallel_4.2.2      numDeriv_2016.8-1.1 compiler_4.2.2
```

### PR DESCRIPTION
**Pull request by clarkliming**
close #261 

on CRAN we don't have this bug as we are using `variable` attribute already

https://github.com/openpharma/mmrm/blob/2fdbb02ca057ab85a6cf2177b459b6c60cabe6dd/R/tmb.R#L147

### CODE REVIEW

File: tests/testthat/test-utils-formula.R [hunk 1]
```diff
@@ -26,6 +26,18 @@ test_that("h_extract_covariance_terms returns a list of possible covariance term
     h_extract_covariance_terms(a ~ a + us(a | g / s)),
     list(us = quote(us(a | g / s)))
   )
+
```
Comment (danielinteractive) [inline tests/testthat/test-utils-formula.R:29]: maybe does not hurt to add an integration test for the concrete user bug in the relevant test file?

**Comment by clarkliming** [comment]
thank you @danielinteractive I was too confident with the fix. it do have other bugs. I think it is related to base R, see the following

```{r}
a = FEV1 ~ ARMCD:USUBJID + VISIT
b <- terms(a)
d <- drop.terms(b, dropx = 1, keep.response = TRUE)
formula(d)
d <- drop.terms(b, dropx = 2 , keep.response = TRUE)
formula(d)
d <- drop.terms(b, dropx = 3 , keep.response = TRUE)
formula(d)
```
it gives
```
FEV1 ~ ARMCD:USUBJID

FEV1 ~ VISIT

FEV1 ~ VISIT + ARMCD:USUBJID
```

however

```{r}
a = FEV1 ~ ARMCD + VISIT
b <- terms(a)
d <- drop.terms(b, dropx = 1, keep.response = TRUE)
formula(d)
d <- drop.terms(b, dropx = 2 , keep.response = TRUE)
formula(d)
d <- drop.terms(b, dropx = 3 , keep.response = TRUE)
formula(d)
```
gives

```
FEV1 ~ VISIT

FEV1 ~ ARMCD

FEV1 ~ ARMCD + VISIT
```

**Comment by danielinteractive** [comment]
Thanks @clarkliming , can you add tests and fixes for the additional problems? since these are also about interaction term models it fits within this PR

**Review by danielinteractive — APPROVED** [review]

**Comment by clarkliming** [comment]
maybe @danielinteractive also have a look at the bug from base R, and check if we should reach out to R team for this issue ( or, we are not using this functionality correctly?)

**Comment by danielinteractive** [comment]
Thanks Liming, hm yeah as long as we don't use this here then no pressing need. If you are curious you could post to the R help mailing list and see what people reply. Bug reports to R have pretty high bar if I remember correctly.
